FROM golang:1.21.1-alpine3.18 as builder

WORKDIR /app

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY *.go .
COPY .env ./

RUN CGO_ENABLED=0 GOOS=linux go build -o ./main

FROM scratch

WORKDIR /app

COPY --from=builder /app/main ./
COPY --from=builder /app/.env ./

EXPOSE 2468

CMD ["./main"]